// what-to-eat-website/src/components/BottomNavbar.vue
<script lang="ts">
    import { ref } from 'vue';

    import bookmarkIcon from '../assets/bookmark.png'
</script>

<template>
    <div class="h-20 w-full mx-auto flex flex-row justify-between items-center px-5">
        <div class="border-b py-2 border-black cursor-pointer">
            <img class="h-8 hover:scale-105" src="../assets/discover.png" alt="" />
        </div>
        <div class="py-2 border-black cursor-pointer">
            <img class="h-8 hover:scale-105" src="../assets/bookmark.png" alt="" />
        </div>
        <div class="py-2 border-black cursor-pointer">
            <img class="h-8 hover:scale-105" src="../assets/bookmarks.png" alt="" />
        </div>
        <div class="py-2 border-black cursor-pointer">
            <img class="h-8 hover:scale-105" src="../assets/settings.png" alt="" />
        </div>
    </div>   
</template>

// what-to-eat-web/src/components/BottomNavbar.tsx
import { settingsIcon, bookmarkIcon, bookmarksIcon, discoverIcon } from "../assets/exports";

const BottomNavbar = () => {
    return (
        <div className="h-20 w-full mx-auto flex flex-row justify-between items-center px-5">
            <div className="border-b py-2 border-black">
                <img className="h-8" src={discoverIcon} alt="" />
            </div>
            <div className="py-2 border-black">
                <img className="h-8" src={bookmarkIcon} alt="" />
            </div>
            <div className="py-2 border-black">
                <img className="h-8" src={bookmarksIcon} alt="" />
            </div>
            <div className="py-2 border-black">
                <img className="h-8" src={settingsIcon} alt="" />
            </div>
        </div>   
    )
}

export default BottomNavbar;
